site_name: Mojentic
theme:
  name: material
  features:
    - content.code.copy
    - content.code.select
  palette:
    primary: custom
    accent: custom
  custom_dir: docs/overrides
  logo: assets/mojility_favicon.png
  favicon: assets/mojility_favicon.png
plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          paths: [ "src" ]
          import:
            - https://docs.python.org/3/objects.inv
            - https://docs.pydantic.dev/latest/objects.inv
            - https://jcristharif.com/msgspec//objects.inv
          options:
            docstring_style: "numpy"
            heading_level: 1
            annotations_path: brief
            extensions:
              - griffe_fieldz
      enable_inventory: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Home: index.md
  - Using LLMs: broker.md
  - Layer 1 - Core:
    - Getting Started with Layer 1: starter_1.md
    - Examples and Tutorials (Layer 1):
      - Simple Text Generation: simple_text_generation.md
      - Building Chatbots: chat_sessions.md
      - Structured Output: structured_output.md
      - Building Tools: building_tools.md
      - Tool Usage: tool_usage.md
      - Building Chatbots with Tools: chat_sessions_with_tools.md
      - Image Analysis: image_analysis.md
  - Layer 2 - Agents:
      - Iterative Problem Solver: ipa.md
      - Simple Recursive Agent: sra.md
  - API Documentation:
      - Intro: api_0.md
      - Layer 1: api_1.md
      - Layer 2: api_2.md
  - Contributing:
      - testing.md

repo_name: mojility/mojentic
repo_url: https://github.com/mojility/mojentic
