[project]
name = "mojentic"
version = "0.2.0"
authors = [
    { name = "Stacey Vetzal", email = "stacey@vetzal.com" },
]
description = "Mojentic is an agentic framework that aims to provide a simple and flexible way to assemble teams of agents to solve complex problems."
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    'Programming Language :: Python :: 3',
    'License :: OSI Approved :: MIT License',
    'Operating System :: OS Independent',
]

[project.dependencies]
python = ">=3.11"
pydantic = ">=2.10.6"
structlog = ">=25.1.0"
ollama = ">=0.4.7"
openai = ">=1.61.0"
tiktoken = ">=0.8.0"
parsedatetime = ">=2.6.0"
pytz = ">=2025.1"
serpapi = ">=0.1.5"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[project.urls]
Homepage = "https://github.com/mojility/mojentic"
Issues = "https://github.com/mojility/mojentic/issues"

